version: '3.7'

services: 

  melita-gateway-service:
    restart: always
    image: mickeydluffy/gateway-service:latest
    container_name: melita-gateway-service
    environment:
     - SPRING_PROFILE=dev
    ports:
      - '5000:8080'
    depends_on:
      - melita-config-server
    networks:
      - melita-network

  melita-order-tracking-service:
    restart: always
    image: mickeydluffy/melita-order-tracking-service:latest
    container_name: melita-order-tracking-service
    environment:
     - SPRING_PROFILE=dev
    ports:
      - '5001:8080'
    depends_on:
      - melita-config-server
    networks:
      - melita-network


  melita-care-system:
    restart: always
    image: mickeydluffy/care-system:latest
    container_name: melita-care-system
    environment:
     - SPRING_PROFILE=dev
    ports:
      - '5002:8080'
    depends_on:
      - melita-config-server
    networks:
      - melita-network


  melita-order-fullfilment-system:
    restart: always
    image: mickeydluffy/order-fullfilment-system:latest
    container_name: melita-order-fullfilment-system
    environment:
     - SPRING_PROFILE=dev
    ports:
      - '5003:8080'
    depends_on:
      - melita-config-server
    networks:
      - melita-network


  melita-authorization-server:
    restart: always
    image: mickeydluffy/authorization-server:latest
    container_name: melita-authorization-server
    environment:
     - SPRING_PROFILE=dev
    ports:
      - '5004:8080'
    depends_on:
      - melita-config-server
    networks:
      - melita-network


  melita-config-server:
    restart: always
    image: mickeydluffy/config-server:latest
    container_name: melita-config-server
    ports:
      - '5005:8080'
    networks:
      - melita-network


  melita-mongodb-server: 
    image: mongo:6.0
    container_name: melita-mongodb-server
    restart: always
    ports:
      - '27017:27017'

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    container_name: kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - melita-network

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - melita-network

networks:
  melita-network:
    driver: bridge