server:
  error:
    include-stacktrace: never
spring:
  application:
    name: melita-care-system
  profiles:
    active:
      - ${SPRING_PROFILE}

---

server:
  port: ${gateway-service-port}
spring:
  config:
    activate:
      on-profile:
        - local
    import: optional:configserver:http://localhost:5005

com:
  melita:
    kafka:
      topic: orders
---

server:
  port: 8088
spring:
  config:
    activate:
      on-profile:
        - dev
    import: optional:configserver:http://localhost:5005

com:
  melita:
    kafka:
      topic: orders